variables:
  COMPOSER_CACHE_DIR: .composer-cache

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - .composer-cache

stages:
  - test

test:
  stage: test
  tags:
      - php
  before_script:
    - apt-get update -qq && apt-get -qq -o dir::cache::archives="apt-cache" install -y php5 php5-cli php5-curl zip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  script:
    - composer install
    - bin/phpunit --bootstrap vendor/autoload.php tests/*
